language: csharp
solution: InteractiveOfficeClient.sln
mono:
  - latest

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
